apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ope-log-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ope-log-collector
subjects:
- kind: ServiceAccount
  name: ope-log-collector
  namespace: rhods-notebooks
