apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration 
metadata:
  name: assign-class-label-webhook
webhooks:
- name: assign-class-label-webhook.nerc.com
  clientConfig: 
    service:
      namespace: ope-rhods-testing-1fef2f
      name: assign-class-label-webhook
      path: /mutate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURxekNDQXBPZ0F3SUJBZ0lVT1ZseDVzTnpXSzA0TVVoVVJVWVdlUXBiTWlvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1FqRUxNQWtHQTFVRUJoTUNXRmd4RlRBVEJnTlZCQWNNREVSbFptRjFiSFFnUTJsMGVURWNNQm9HQTFVRQpDZ3dUUkdWbVlYVnNkQ0JEYjIxd1lXNTVJRXgwWkRBZUZ3MHlOREE0TWpreE9EQTJNRFZhRncweU56QTJNVGt4Ck9EQTJNRFZhTUVJeEN6QUpCZ05WQkFZVEFsaFlNUlV3RXdZRFZRUUhEQXhFWldaaGRXeDBJRU5wZEhreEhEQWEKQmdOVkJBb01FMFJsWm1GMWJIUWdRMjl0Y0dGdWVTQk1kR1F3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQgpEd0F3Z2dFS0FvSUJBUUN5WmxLeWdzVW8zS2g2VThGVEFQNGViQ25wRHNuU1hmUjZHUCtlSGJBU2xGZVBTU2hRCkJJQzJKcytMb3Vpd0F0VkRJblRnRWVzZXZSS3FWdHhveDQwSEdhakVoUkRDNTZKWjNtKzl2L1ZJcDhMeWtic00KSmFQakRwWUJKczBJWm1zaFlMaFBtT3JOSmFZbWJlL25IeFNHcGhXWjE5TlVKcjg0Qm4zSmdTZTkwekZwbGszTQpGbEF5UmY1eDVIbTk4UzhhS3RVeHh5RjAvaXNBK3RFbmgvL0c3aWs4QndCT2lFS1A4cTluaG1EVnZDOURXTkJMCkRZNjFEOWtKQmFhQ3RYaGNQNWNGLzBlTUFrc2NKSS9iZkxjc3pIYUhnWW1kUlB6RSsyN3VlckxFZGsrUWdUSGwKcmtuWE85NEdwNG1UZ1lKV2ZwdjFYVmxncVhoRGVyTnhsUjROQWdNQkFBR2pnWmd3Z1pVd0hRWURWUjBPQkJZRQpGTklsbVAwTlhkdW5Fak1IZ3pGcUYxZ1RIYU5ZTUI4R0ExVWRJd1FZTUJhQUZOSWxtUDBOWGR1bkVqTUhnekZxCkYxZ1RIYU5ZTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3UWdZRFZSMFJCRHN3T1lJM1lYTnphV2R1TFdOc1lYTnoKTFd4aFltVnNMWGRsWW1odmIyc3ViM0JsTFhKb2IyUnpMWFJsYzNScGJtY3RNV1psWmpKbUxuTjJZekFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQVFFQVF5Y2xJZ3VCRGhOMWZBQWRKV0R0aDNJb3JydytvQVlOYkxsR0pxY0xnRVVhCjRISnZwb0grTWpqYkRGOTF1QUFyb3g1bXU5c3grVGlySjE1VnRSTnlCeHozbkFQd2F2NmplZHhPbmVTSjVjZlYKNnBZMkNTOEJIa2h1ZWJKWTVRVUM5NzMvNEpsZnY1WlN4OUpZS2d5Yk9McTNSRnlBZ21pZjA1L2w1NzN0MFJraQpCRXUwbHc3OVlXaktBRDluYkRFYUhrajVkTStLcTZrdVZ0T3dlaTBBMlNoc0p1MVVZVEhDdGFxQjNQTDU2dWVBCnhIejJBTlQwdlFNK2lLMFJCUlBLODE2K2ZOQm10TGlpZG1mSi9QWVFxeVdDQnhudWlxQ1B2bzUvcXRmdS9DbzcKNENjUTJaSTV1QWhleGI5b0xWZW5pM2lmTGg1MHV3M1dmZWlyMk8wckJRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - rhods-notebooks
  sideEffects: None
  admissionReviewVersions: ["v1"] 
