apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration 
metadata:
  name: assign-class-label-webhook
webhooks:
- name: assign-class-label-webhook.nerc.com
  clientConfig: 
    service:
      namespace: ope-test
      name: assign-class-label-webhook
      path: /mutate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtekNDQW9PZ0F3SUJBZ0lVYW1jSGEyZVhtVE5oL2tIckp3MEs5RmdwMDRNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1FqRUxNQWtHQTFVRUJoTUNXRmd4RlRBVEJnTlZCQWNNREVSbFptRjFiSFFnUTJsMGVURWNNQm9HQTFVRQpDZ3dUUkdWbVlYVnNkQ0JEYjIxd1lXNTVJRXgwWkRBZUZ3MHlOREE0TWpZeE56UTRNRGxhRncweU56QTJNVFl4Ck56UTRNRGxhTUVJeEN6QUpCZ05WQkFZVEFsaFlNUlV3RXdZRFZRUUhEQXhFWldaaGRXeDBJRU5wZEhreEhEQWEKQmdOVkJBb01FMFJsWm1GMWJIUWdRMjl0Y0dGdWVTQk1kR1F3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQgpEd0F3Z2dFS0FvSUJBUURCN0Z2YTd1Z05mMEJWeHlXRzBTdDJ0RGZWdUJjeUFsaUM4YVEyNlFvSktuNjZOS0VECk9zMWEwODAyaEVxZERaZ3hlYU1Bcys0Y2NkUU9neVVvZ0xBbHVXR0dKYjVyY3B6emlmQmpLVmYvM0NTaG5RUVUKRXc3ZnNmb1I5dzM4NGVIQlgrbmk0WXBZUGhMTVJtS0tsNWFvTzVPWHN5Z2ZwQ3d0NzMyM05GeExXSWhaWVhsVgpqL09sWktsNUdhL0tWSU0zcmE2K2hjc3BiaTFIU2QxNi9RczNERVdBNkUzT0NXM0ZyeStLcmdoNjVqaUhyY1U3Clh1am9ZWCsrT1RiTDh6UEd4NXZIeVR6ZldFRGw2bmlYbkovbGliZ3NKNDBQaWZlYWp3blhMRUNyaWt4R0hyd2kKZFhSbE5FNTMrVFZDUFBWZVdCNGdiL0dOWjE1MGloSFFkK3NUQWdNQkFBR2pnWWd3Z1lVd0hRWURWUjBPQkJZRQpGS3VzYUxNV0hLZUlNVTd1bGljbm5zVDZlUnVPTUI4R0ExVWRJd1FZTUJhQUZLdXNhTE1XSEtlSU1VN3VsaWNuCm5zVDZlUnVPTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3TWdZRFZSMFJCQ3N3S1lJbllYTnphV2R1TFdOc1lYTnoKTFd4aFltVnNMWGRsWW1odmIyc3ViM0JsTFhSbGMzUXVjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDOApoYUxIUEdZckZYYXIxeXhaaVhjQkx0OUtMK0FaVjE4aCtpem01ZnRqbkRRK2g1UXU4eUpEaE85S2Q3bi9YVTh3CkNtRktYeUQxZ2kvU1hwaGhKbGNHblFCQlIxczE5NDNuSkxBVFI3bCtXamZrd05pWkhsc1orN2o0K2VnYkozVnYKUXhyeHlMeG1MVk5WVnp1Y213VFJ0Sm1qRVZLa2ZiWjVHcU56QTE4dWRCYythYjcwdFpzVXFQbXZ5ZmsyWktveAplSGN4b3Mra2g1R3pzaktDL1RabzU0R0RqQXBFNDJnUVkzQW1VcFlsWGFnU2h5VVdRTVEwMmpXRjN3dnlkOTBMCkNQY1RFNmNGVEJoWlFHSFBjN0VBSTdzcjUya0p1UFZGUmUxOXc3MzhSUSttQmdBYlozZHdLcG1oZVRIWndHUUMKVGRUODl5aHRUQngxM0hDOTlWRmcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - rhods-notebooks
  sideEffects: None
  admissionReviewVersions: ["v1"] 
