apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration 
metadata:
  name: validate-ope-pods
webhooks:
- name: validate-ope-pods-webhook.nerc.com
  clientConfig: 
    service:
      namespace: ope-rhods-testing-1fef2f
      name: validate-ope-pods-webhook
      path: /validate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURxakNDQXBLZ0F3SUJBZ0lVTTNEZVRxYmNrbUg5U242SFZRYTIyOEEyUDZJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1FqRUxNQWtHQTFVRUJoTUNXRmd4RlRBVEJnTlZCQWNNREVSbFptRjFiSFFnUTJsMGVURWNNQm9HQTFVRQpDZ3dUUkdWbVlYVnNkQ0JEYjIxd1lXNTVJRXgwWkRBZUZ3MHlOREE0TWpreU16VTVNVFZhRncweU56QTJNVGt5Ck16VTVNVFZhTUVJeEN6QUpCZ05WQkFZVEFsaFlNUlV3RXdZRFZRUUhEQXhFWldaaGRXeDBJRU5wZEhreEhEQWEKQmdOVkJBb01FMFJsWm1GMWJIUWdRMjl0Y0dGdWVTQk1kR1F3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQgpEd0F3Z2dFS0FvSUJBUURzbFN0Zm9lZ3o2MnNDQjVKbFhxOWJISzc5aGVSUFhwRzNvVCsyTktjaVNydnU4YVFwCmkzV2x3MDBFVVJRR3dFckZmNEJzVWM4UXN6QmJ2aFpRV1NsTVh2RnA2dHE2UXV0YUp6NVQxS01oUUo4clo4bmgKT01pZndiZVBTSGFkNDNHR285aXBXbUhNdmNwK21pOU9lU05Ma3ZBaDM4R1d2ZW9oYml0UTBqSk0wMHU2NU95VApsSUhvelo2bHZRR1hiOEkremdRUTJ0RW1md3lRSy9lbHkyMlJJWkZTaE1iaGhlcU91M2l1VFN6WHZOWGxVQWswCjJESHUwZHdFbmVSVTNKNllLRHh4NDI3UG43dU5VeFFRbnAzbjlYcGZJWkhXTEVBQVB2ZEFzTk1PQ3NwRzNvbnEKRUtVdmo3QVNIbEFUaXZDVmpNZjlkVWFLYm03K1dwTXZocTdwQWdNQkFBR2pnWmN3Z1pRd0hRWURWUjBPQkJZRQpGQW91ckdIVTBrZHhBSHh6WDhLSEF1b0RNTlpCTUI4R0ExVWRJd1FZTUJhQUZBb3VyR0hVMGtkeEFIeHpYOEtICkF1b0RNTlpCTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3UVFZRFZSMFJCRG93T0lJMmRtRnNhV1JoZEdVdGIzQmwKTFhCdlpITXRkMlZpYUc5dmF5NXZjR1V0Y21odlpITXRkR1Z6ZEdsdVp5MHhabVZtTW1ZdWMzWmpNQTBHQ1NxRwpTSWIzRFFFQkN3VUFBNElCQVFCVjlXWVlmUlVSWUtIYkVjMmJzbzE3cjRSN1FqdjJ5Lyt0amFGNkltZXlxaERCCnNQc0crV2ZFTG1ZWXpyQTZad0JrOSthcS9ybW93OHVRT0VYL1BmU1RvajhyalVZdFN5aUMzVG5XSzh4dDdMOUIKSmZzMkNiSzlHYk1lLzE2TXNGVUZLRVF4NjZLZ00xRnVxaVNlOVVIZFkyd01iZzlWcjBZL3NOOSt5Sjg5ZlY3agpBVTAwZklyV2N3MWFsM2F6QzVOSzVrY0VRQmZPdU43T1NnS0M5VHY3L2NaTVE0VkJhWFB2OVUrVzNRY0FYM2RZCkNjYVdmTlZ0aWF6d0s0cWtZMXBIWkNwV1ZEcjkxWHZveWo2Nnl3cmdGeDI2M3B1SjhFRmJRRTZZbGZHS2ZsMksKNkpmZXJ5SlUvMlhkaEJ4c1BQSjByQTFiRTBBUUkyYUc0eXJpYndGZwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - rhods-notebooks
  sideEffects: None
  admissionReviewVersions: ["v1"] 
